name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Install Playwright browsers (Chromium only)
      - name: Install Playwright Chromium
        run: npx playwright install chromium

      # 5. Run Playwright tests (Chromium)
      - name: Run Playwright tests
        run: npx playwright test --project=chromium --reporter=list,allure-playwright

      # 6. Upload Playwright HTML report
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30

      # 7. Upload Allure results
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 30
